# Generated by Django 4.0.5 on 2022-06-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myopsuser',
            name='user_photo',
        ),
    ]
