# Generated by Django 4.0.5 on 2022-06-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myopsuser',
            name='first_name',
            field=models.CharField(default='John', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myopsuser',
            name='last_name',
            field=models.CharField(default='Doe', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myopsuser',
            name='username',
            field=models.CharField(default='jdoe', max_length=30),
            preserve_default=False,
        ),
    ]
