# Generated by Django 4.0.5 on 2022-06-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_myopsuser_first_name_myopsuser_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='tip',
            new_name='tip_id',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='user_id',
        ),
    ]
