# Generated by Django 4.0.5 on 2022-06-07 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_remove_myopsuser_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.tip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.myopsuser')),
            ],
        ),
    ]
