# Generated by Django 4.0.5 on 2022-06-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_rename_tip_id_favorite_tip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='favorites',
            field=models.ManyToManyField(related_name='favoritedtips', through='app_api.Favorite', to='app_api.myopsuser'),
        ),
    ]
