# Generated by Django 4.0.5 on 2022-06-08 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_alter_tip_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='break_time',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='exercise_time',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='learning_time',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='personal_time',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='sleep_time',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='work_time',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
    ]
