# Generated by Django 4.0.5 on 2022-06-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_alter_checkin_break_time_alter_checkin_exercise_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.mood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.myopsuser')),
            ],
        ),
    ]
