# Generated by Django 4.0.5 on 2022-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
